# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='desc',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
