# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical', '0002_auto_20170424_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='desc',
            field=models.TextField(blank=True, db_index=True, max_length=100),
        ),
    ]
